[package]
name = "aas-submodel-abstraction"
version = "1.0.0"
edition = "2024"

[dependencies]
aas-model-rs = { git = "https://github.com/NoName11234/aas-model-rs", branch = "releases/1.2.0" }
serde = {version = "1.0", features = ["derive"]}